name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Formatting checks
      run: cargo fmt --all -- --check
    - name: Clippy checks
      run: cargo clippy --all-targets -- -D clippy::all -D clippy::cargo  -A clippy::multiple-crate-versions
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

# Recommended pipeline if using advisories, to avoid sudden breakages
# From: https://github.com/EmbarkStudios/cargo-deny-action
  cargo-deny:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
    - uses: actions/checkout@v4
    - uses: EmbarkStudios/cargo-deny-action@v1
      with:
        command: check ${{ matrix.checks }}
